apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-custom
  template:
    metadata:
      labels:
        app: python-custom
    spec:
      containers:
      - name: python-custom
        image: python
        command: ["bash","-c"]
        args:
          - |
            pip install stomp.py
            python -u /home/custom-metric-exporter.py
#        command: ["pip install stomp.py && python3"]
#        args:
#         - -u
#         - '/home/custom-metric-exporter.py'
        volumeMounts:
        - name: script-volume # This name must match a volume below
          mountPath: /home # Directory where files will appear
      volumes:
      - name: script-volume # A unique name for this volume within the Pod
        configMap:
          # Specify the name of the ConfigMap to use
          name: custom-metric-config
