apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stressng
  template:
    metadata:
      labels:
        app: stressng
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: stressng
#        image: lorel/docker-stress-ng
        image: alexeiled/stress-ng
        args:
        - --cpu
        - '0'
        - --cpu-method
        - pi
        - -l
        - '20'
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: stressng
spec:
  type: NodePort
  selector:
    app: stressng
  ports:
  - name: port-80
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  - name: port-443
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443
