apiVersion: v1
data:
  # SAT_FILE: {{ sat_file }}
  SAT_FILE: {{ sat_file }}
  OPTIMUSDB_URL: {{ optimusdb_url }}
  USE_KB: "{{ 'true' if use_kb else 'false' }}"
kind: ConfigMap
metadata:
  name: emsconfig
  namespace: default
