apiVersion: v1
kind: Pod
metadata:
  name: python-shell
  namespace: swarm-system
  labels:
    app: mon-client-test
spec:
  serviceAccountName: mon-client
  restartPolicy: Never
  containers:
    - name: python-shell
      image: python:3.14-slim
      command: ["bash", "-lc", "sleep infinity"]
      stdin: true
      tty: true
