apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-seconds-counter
  labels:
    app: python-seconds-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-seconds-counter
  template:
    metadata:
      labels:
        app: python-seconds-counter
    spec:
      containers:
        - name: counter
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "-c"]
          args:
            - |
              import time

              seconds = 0
              while True:
                  print(f"seconds={seconds}")
                  time.sleep(1)
                  seconds += 1
