apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raw-local-listener
  labels:
    app: raw-local-listener
spec:
  selector:
    matchLabels:
      app: raw-local-listener
  template:
    metadata:
      labels:
        app: raw-local-listener
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: raw-local-listener
          image: cloud-193-225-250-99.sztaki.science-cloud.hu/swarchestrate/mon_lib:test
          imagePullPolicy: Always
          env:
            - name: MON_CLIENT_STOMP_PORT
              value: "61610"
            - name: MON_CLIENT_STOMP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stomp-credentials
                  key: username
                  optional: true
            - name: MON_CLIENT_STOMP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stomp-credentials
                  key: password
                  optional: true
